### ISSUE TITLE
PDCIDFont.getWidth() without W entry

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-parser#186]
The implementation of PDCIDFont.getWidth() looks wrong to me: If the W entry is missing, that function returns 0, but it should use the DW entry (or 0 if DW is also missing).

ISO 32000-1:2008, Table 117, W:

  Default value: none (the DW value shall be used for all glyphs).

**Comment by bdoubrov** [comment]
Agree. Looks like a bug. 

Thanks for reporting this.
