### ISSUE TITLE
Add extra data into features report

### ISSUE THREAD

**Issue by bdoubrov** [veraPDF/veraPDF-parser#212]
It would be nice to have the following information in the feature report:

- Page labels for pages
- Names and values for the interactive form fields

**Comment by BezrukovM** [comment]
Added in PRs:
https://github.com/veraPDF/veraPDF-library/pull/776
https://github.com/veraPDF/veraPDF-validation/pull/185
https://github.com/veraPDF/veraPDF-pdfbox-validation/pull/159
