### ISSUE TITLE
Wrong message if document catalog's Type entry is missing

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-parser#222]
If the document catalog's Type entry is missing, veraPDF says (test 1 of 6.7.2 for PDF/A-1B):

"The document catalog dictionary of a conforming file shall contain the Metadata key."

However, in this sample document:

[NoType.pdf](https://github.com/veraPDF/veraPDF-parser/files/1021578/NoType.pdf)

the Metadata key is present. What's missing is the Type key.

**Comment by shem-sergey** [comment]
Hello! Thanks for this issue.
The problem that occurs is not with our pdf parser but with PDFBOX parser, if you validate the file with the latest version (http://downloads.verapdf.org/rel/1.4/verapdf-1.4.6-installer.zip) then verapdf confirms compliance with 1b.
So probably you are using PDFBOX version. This version is getting obsolete with the development of our own pdf parser.

**Comment by a20god** [comment]
Thanks!
