### ISSUE TITLE
StandardFontMetricsFactory not usable within ApplicationServer

### ISSUE THREAD

**Issue by mirehasfun** [veraPDF/veraPDF-parser#312]
In our application, we deploy the veraPDF-validation-model within a WAR in an application server (WildFly 10). 

When validating a certain PDF, at some point the code runs through StandardFontMetricsFactory.getFontMetrics() with a parameter "Helvetica". Since the FONT_METRICS_MAP is not filled at that point, it tries to load() the font metrics from the jar. 

This is where the issue happens: the URL of the resource does **not** start with "jar:" but with "vfs:", causing the code run through the wrong branch - whereas the same branch as for the "jar:" loading would work seamlessly. 

More specific, the URL looks like this 

> "vfs:/content/my.war/WEB-INF/lib/parser-1.8.1.jar/font/stdmetrics/Helvetica.afm"

I could provide a Pull request or a patch with a more generic solution that should work in all environments.

**Comment by BezrukovM** [comment]
@mirehasfun yes, please. If it's not much trouble, provide a pull request.

**Comment by mirehasfun** [comment]
I'd be glad to. 
Which branch should I use as baseline? master or integration?

**Comment by BezrukovM** [comment]
integration

**Comment by mirehasfun** [comment]
Created #313

**Comment by BezrukovM** [comment]
PR merged. New dev version: 1.9.46
