### ISSUE TITLE
the parser doesn’t seem to recognize color profile inside /XObject /Resources

### ISSUE THREAD

**Issue by ousia** [veraPDF/veraPDF-parser#317]
I have the following [uncompressed PDF/A-3a document](https://github.com/veraPDF/veraPDF-parser/files/1385575/unrgb.pdf).

The parser version 1.9.45 complains about [`/XObject /Form` not having any ICC profile](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Parts-2-and-3-rules#rule-6243-2).

The PDF document contains both a bitmap image (`/XObject /Image`) and a vector image (`/XObject /Form`).

This is the image external object:

```
12 0 obj
<<
  /Type /XObject
  /Subtype /Image
  /Width 506
  /Height 45
  /BitsPerComponent 8
  /Length 68310
  /ColorSpace /DeviceRGB
>>
stream
endstream
endobject
```

This is the form external object:

```
13 0 obj
<<
  /Type /XObject
  /Subtype /Form
  /FormType 1
  /BBox [ 0 0 957.48 859.44 ]
  /Resources <<
    /ProcSet [ /PDF ]
    /ExtGState 25 0 R
    /ColorSpace 8 0 R
  >>
  /Length 445
>>
stream
endstream
endobject
```

I have added the color space to the resource dictionary by hand and compressed the PDF document again.

The parser complains about missing color profile in object 13, but not in object 12.

I also added `/ColorSpace /DeviceRGB`, obtaining the same results.

Table 33 on [page 83](https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf#page=91) from the PDF Reference lists `/ColorSpace` as one entry for the `/Resource` dictionary.

I think this might be a bug in the parser.

Many thanks for your help.

**Comment by bdoubrov** [comment]
The issue with the document is that the content stream of Form XObject (object 13 0) uses DeviceRGB colour space, while the document does not contain the RGB output intent.

I see that there is /DefaultRGB color space specified in the Page resources dictionary. However, it is not applicable to the operators in the Form XObject.  The easiest way to fix would be to add this /DefaultRGB definition to the Form XObject resources.

**Comment by ousia** [comment]
@bdoubrov, many thanks for your reply. Since I have to explain it to other people, I have to understand what was wrong there.

> The issue with the document is that the content stream of Form XObject (object 13 0) uses DeviceRGB colour space, while the document does not contain the RGB output intent.

Sorry, but I think the document (`/Catalog`, object 32) does contain the RGB output intent as indirect object (31). This refers to object 11 (`/Type /OutputIntent`).

What am I missing there?

> I see that there is /DefaultRGB color space specified in the Page resources dictionary. However, it is not applicable to the operators in the Form XObject. The easiest way to fix would be to add this /DefaultRGB definition to the Form XObject resources.

The page (object 14) ressource dictionary points to an indirect object (21), which contains a color space object reference (`2 0 R`).

Rewriting the object:

```
13 0 obj
<<
  /Type /XObject
  /Subtype /Form
  /FormType 1
  /BBox [ 0 0 957.48 859.44 ]
  /Resources <<
    /ProcSet [ /PDF ]
    /ExtGState 25 0 R
    /ColorSpace 2 0 R
  >>
  /Length 445
>>
stream
endstream
endobject
```

This works fine with color profiles. Is this what you meant?

(I have a further question about a general method to do this.)

**Comment by ousia** [comment]
I have another [uncompressed PDF document](https://github.com/veraPDF/veraPDF-parser/files/1404241/uncompressed-xobject-noicc.pdf). it contains only a form external object:

```
12 0 obj
<<
  /Type /XObject
  /Subtype /Form
  /FormType 1
  /BBox [ 0 0 957.48 859.44 ]
  /Resources <<
    /ProcSet [ /PDF ]
    /ExtGState 22 0 R
  >>
  /Length 445
>>
stream
endstream
endobject
```

The parser complaints about missing RGB color profile for the object.

It makes no difference when I add `/ColorSpace 2 0 R` to its `/Resources` dictionary of the object.

Is this a bug in the parser or what is wrong in the document?

**Comment by bdoubrov** [comment]
I think I found out the reason for the color space issues in your document. The OutputIntent dictionary has subtype `GTS_PDFA3`:
> /S /GTS_PDFA3

But it should be `PDFA1` for all PDF/A parts. As soon as this is fixed, any DefaultRGB or DefaultGray entries in the resource dictionary become redundant. 

Note also that the documents you attach have other PDF/A issues in the header and in some spacing requirements. But they might be the result of the PDF uncompress tool you use.

**Comment by ousia** [comment]
@bdoubrov, many thanks for the reply.

It would have taken years to me to discover this issue.

The spacing issues you mention in your last paragraph are caused by the decompression tool. They aren’t part of the original PDF document.

Many thanks again for your help (closing the issue myself).
