### ISSUE TITLE
Glyph widths information - inconsistent between parsers?

### ISSUE THREAD

**Issue by wangp** [veraPDF/veraPDF-parser#324]
The following relates to this test case: [noto1.pdf](https://github.com/veraPDF/veraPDF-parser/files/1444863/noto1.pdf)

verapdf-pdfbox-1.9.60 reports that the file is compliant with PDF/A-1B.

verapdf-greenfield-1.9.60 reports that it fails on clause 6.3.6: "For every font embedded in a conforming file and used for rendering, the glyph width information in the font dictionary and in the embedded font program shall be consistent." 

I have been unable to figure out what triggers the failure. Apologies if this is reported in the wrong place.

**Comment by wangp** [comment]
Thanks!

**Comment by wangp** [comment]
I assume the fix is included in the 1.9.61 downloads. However, the same issue occurs with this test case: 
[arno1.pdf](https://github.com/veraPDF/veraPDF-parser/files/1459696/arno1.pdf)

**Comment by BezrukovM** [comment]
@wangp thanks for new bug founded and for such situations feel free to reopen issues.

**Comment by wangp** [comment]
@BezrukovM Thank you. There are still problems with these test cases:
[noto1a.pdf](https://github.com/veraPDF/veraPDF-parser/files/1469130/noto1a.pdf)
[arno2.pdf](https://github.com/veraPDF/veraPDF-parser/files/1469121/arno2.pdf)

(I cannot reopen the issue.)

**Comment by BezrukovM** [comment]
Fixed in veraPDF 1.6.63. 
I will not close this issue for now.
@wangp, when you will not find any more files with similar problems, then feel free to close this issue (or left here a comment that everything is ok and I will close it by myself).
Thanks

**Comment by wangp** [comment]
I did not find any problems using some fonts I had available. Thanks again.
