### ISSUE TITLE
ToUnicode cmap

### ISSUE THREAD

**Issue by wangp** [veraPDF/veraPDF-parser#329]
Hi,
verapdf-pdfbox-1.9.75 accepts these files as compliant with PDF/A-1A, but verapdf-greenfield-1.9.75 does not.

[times.pdf](https://github.com/veraPDF/veraPDF-parser/files/1500650/times.pdf)
[ezra.pdf](https://github.com/veraPDF/veraPDF-parser/files/1500651/ezra.pdf)

The failed rule is Specification: ISO 19005-1:2005, Clause: 6.3.8, Test number: 1
"The font dictionary shall include a ToUnicode entry whose value is a CMap stream object that maps character codes to Unicode values, as described in PDF Reference 5.9, unless the font meets any of the following three conditions: ..."

**Comment by BezrukovM** [comment]
fixed. look at veraPDF GF 1.9.76
