### ISSUE TITLE
Problem with parsing when stream has certain length. Last character in stream is lost.

### ISSUE THREAD

**Issue by arctaedius** [veraPDF/veraPDF-parser#331]
I found a problem with veraPdf when parsing streams within the pdf and the stream is of a certain size.

When the stream has a multiple of this specific size, the last character in the stream is lost causing problem with the parsing since the parser won't recognize the last command if a character is missing.

I think the problem is in the ASBufferedInFilter class' readFromStreamToBuffer method.
If read() returns -1 (which might occur for certain sizes of the stream) the eod is set to a value one less than the actual end of data.

One way to solve this might be 

```
  private void readFromStreamToBuffer(int offset, int len) throws IOException {
    int read = getInputStream().read(buffer, offset, len);
    if (read < len) {
      // TODO: in fact, read may be less then len even if eof is not reached.
      // Fix problem for this case.
      eod = offset + (read != -1 ? read : 0);
    }
  }
```

I tested it with a file of length 1537 and then the last character was never read by the ASBufferedInFilter.readByte() method.

(I can of course provide a simple test case if that would help?)

**Comment by BezrukovM** [comment]
@arctaedius thanks for founded bug. Yes, your logic fix looks right.
Can you provide us a test case, please? It would be great to test that fix before creating a hotfix.

**Comment by arctaedius** [comment]
Yes, I will provide the test case on Tuesday. I am away during the weekend. Can you release a fix on the 1.8.1 branch? And will it be available in the maven repository?

**Comment by carlwilson** [comment]
Hi @arctaedius, we're now on v1.10 and would be able to provide a hotfix for that for sure. We could do the same for 1.8 I guess if that's really necessary. Your comment lead me to realise that there's a 1.8.2 hotfix that isn't on Maven central. Not sure why but will rectify. Any 1.10 fix will be on Maven. That's a long winded way of asking you if a 1.10 fix will suffice?

**Comment by jorander** [comment]
Hi @carlwilson,
I'm working together with @arctaedius. Thank you for the prompt response. Yes a 1.10-fix would be great. We hadn't realised there was a 1.10.x of the validation-model released. We will be happy to upgrade.

**Comment by carlwilson** [comment]
Hi @jorander no problem, expect the fix next week.

**Comment by arctaedius** [comment]
[ASBufferedInFilterTest.txt](https://github.com/veraPDF/veraPDF-parser/files/1524627/ASBufferedInFilterTest.txt)

Uploaded a unit tests that fails with current implementation.

**Comment by BezrukovM** [comment]
fixed in 1.10.3 version of parser (1.10.4 version of application)

**Comment by arctaedius** [comment]
Thanks for the update! Will you post a new version of the jar to the maven repository?

**Comment by carlwilson** [comment]
Hi @arctaedius the fix should come down through Maven central today, it takes a little time to clear staging. They're already available on our own development repo: http://artifactory.openpreservation.org/artifactory/list/vera-dev/org/verapdf/.
