### ISSUE TITLE
Type1 font built-in StandardEncoding is being ignored

### ISSUE THREAD

**Issue by kurti42** [veraPDF/veraPDF-parser#339]
Using the greenfield parser verapdf is complaining about missing glyphs in the embedded type1 font, with the pdfbox parser verapdf says the document is valid 1b.

I tried to debug this problem and traced it to the PSParser not recognizing the built-in StandardEncoding and therefore not setting the Encoding entry in the UserDict.

[test.pdf (created with libreoffice 5.1.6.2)](https://github.com/veraPDF/veraPDF-parser/files/1720991/test.pdf)

**Comment by bdoubrov** [comment]
Thanks for the detailed analysis. We'll fix this issue in the coming update
