### ISSUE TITLE
logical structure tree in object stream

### ISSUE THREAD

**Issue by wangp** [veraPDF/veraPDF-parser#354]
veraPDF seems unable to see structure tree root object when it is contained with in an object stream (at least in a hybrid-reference PDF file).

For this example: [object-stream.pdfa3a.pdf](https://github.com/veraPDF/veraPDF-parser/files/1949793/object-stream.pdfa3a.pdf)

veraPDF reports: _The logical structure of the conforming file shall be described by a structure hierarchy rooted in the StructTreeRoot entry of the document's Catalog dictionary, as described in ISO 32000-1:2008, 14.7._ However object 4 (the StructTreeRoot) exists within object 15 (an object stream).

**Comment by BezrukovM** [comment]
Fixed in dev (veraPDF 1.13.2)
